CREATE TABLE stg.partner_accounts (
    ID INT NOT NULL,
    PARTNER_ID INT NOT NULL,
    CREATED_DATE DATETIME2 NOT NULL,
    UPDATED_DATE DATETIME2 NOT NULL,
    CURRENCY NVARCHAR(50) NOT NULL,
    LEDGER_REFERENCE NVARCHAR(50) NOT NULL,
    LEDGER_SCHEME NVARCHAR(50) NOT NULL,
    LEDGER_FLOAT_REFERENCE NVARCHAR(100) NOT NULL,
    FUNDING_TYPE NVARCHAR(50) NOT NULL,
    T0AUDITKEY BIGINT NOT NULL
);

CREATE TABLE stg.partners (
    ID INT NOT NULL,
    GUID NVARCHAR(100) NOT NULL,
    CREATED_DATE DATETIME2 NOT NULL,
    NAME NVARCHAR(100) NOT NULL,
    IDENTITY_USER_GUID NVARCHAR(100) NOT NULL,
    DRIVER NVARCHAR(100) NOT NULL,
    DRIVER_URL NVARCHAR(500) NULL,
    PARTNER_HMAC_SECRET NVARCHAR(500) NULL,
    TYPE NVARCHAR(50) NOT NULL,
    SMS_TEMPLATE VARCHAR(MAX) NULL,
    T0AUDITKEY BIGINT NOT NULL
);

CREATE TABLE stg.payout_locations (
    ID INT NOT NULL,
    TITLE NVARCHAR(100) NOT NULL,
    ADDRESS NVARCHAR(500) NULL,
    SHORT_NAME NVARCHAR(50) NOT NULL,
    COUNTRY_CODE NVARCHAR(50) NOT NULL,
    TYPE NVARCHAR(50) NOT NULL,
    T0AUDITKEY BIGINT NOT NULL
);

CREATE TABLE stg.payout_locations_products (
    PRODUCT_ID INT NOT NULL,
    PAYOUT_LOCATION_ID INT NOT NULL,
    T0AUDITKEY BIGINT NOT NULL
);

CREATE TABLE stg.products (
    ID INT NOT NULL,
    PARTNER_ID INT NOT NULL,
    PROVIDER_ID INT NOT NULL,
    CREATED_DATE DATETIME2 NOT NULL,
    ENABLED BIT NOT NULL,
    GUID NVARCHAR(300) NOT NULL,
    PROVIDER_PRODUCT_ID INT NOT NULL,
    MODIFIED_DATE DATETIME2 NOT NULL,
    COUNTRY_ID INT NOT NULL,
    TITLE NVARCHAR(300) NOT NULL,
    CATEGORY NVARCHAR(100) NOT NULL,
    TYPE NVARCHAR(50) NOT NULL,
    SETTLEMENT_CURRENCY NVARCHAR(50) NOT NULL,
    LOWEST_DENOMINATION NVARCHAR(50) NOT NULL,
    SOURCEOFFUNDS NVARCHAR(MAX) NOT NULL,
    PAYOUT_CURRENCY NVARCHAR(50) NOT NULL,
    ORDERPURPOSES NVARCHAR(MAX) NOT NULL,
    MIN_AMOUNT NVARCHAR(MAX) NULL,
    MAX_AMOUNT NVARCHAR(MAX) NULL,
    SENDER_REQUIREMENTS NVARCHAR(MAX) NULL,
    RECIPIENT_REQUIREMENTS NVARCHAR(MAX)  NULL,
    RECIPIENT_VALIDATION_REQUIREMENTS NVARCHAR(MAX) NULL,
    T0AUDITKEY BIGINT NOT NULL
);

CREATE TABLE stg.providers (
    ID INT NOT NULL,
    NAME NVARCHAR(100) NOT NULL,
    T0AUDITKEY BIGINT NOT NULL
);

CREATE TABLE stg.transactions (
    ID INT NOT NULL,
    PARTNER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    CREATED_DATE DATETIME2 NOT NULL,
    PROVIDER_REFERENCE INT NULL,
    STATUS NVARCHAR(50) NOT NULL,
    COLLECTION_INSTRUCTIONS VARCHAR(MAX) NULL,
    PROVIDER_CALCULATION NVARCHAR(MAX) NULL,
    EXTERNAL_REFERENCE NVARCHAR(200) NOT NULL,
    CALCULATION_TOKEN NVARCHAR(MAX) NOT NULL,
    CALLBACK_URL NVARCHAR(MAX) NOT NULL,
    SENDER NVARCHAR(MAX) NOT NULL,
    RECIPIENT NVARCHAR(MAX) NOT NULL,
    TIMELINE NVARCHAR(MAX) NOT NULL,
    CALLBACKS NVARCHAR(MAX) NOT NULL,
    SOURCE_OF_FUNDS NVARCHAR(50) NULL,
    ORDER_PURPOSE NVARCHAR(50) NULL,
    ERROR VARCHAR(MAX) NULL,
    PAY_IN_AMOUNT NVARCHAR(MAX) NOT NULL,
    CREATED_BY_ID TINYINT NOT NULL,
    PARTNER_ACCOUNT_ID INT NULL,
    PAYMENT_REFERENCE NVARCHAR(100) NULL,
    T0AUDITKEY INT NOT NULL
);